### ISSUE TITLE
maybe a bug in recursive-rox? 

### ISSUE THREAD

**Issue by JSchmidt63** [fishedee/antd-formily-boost#5]
Hi brother,
i love those components. Great work indeed.

Look at the pic, i see no actions when clicking it.

https://fishedee.github.io/antd-formily-boost/components/table/recursive-row
![components-table-recursive-row-2021-11-02](https://user-images.githubusercontent.com/25293774/139825954-a0c596a1-b435-493c-a0b3-48feb88243b9.png)

![components-table-children-row](https://user-images.githubusercontent.com/25293774/139827050-d25bd5f5-6411-4c74-88c1-0add30768129.png)

Cheers

**Comment by JSchmidt63** [comment]
and this as well
https://fishedee.github.io/antd-formily-boost/components/table/children-r
![components-table-children-row](https://user-images.githubusercontent.com/25293774/139827050-d25bd5f5-6411-4c74-88c1-0add30768129.png)
ow

**Comment by fishedee** [comment]
Thanks,brother, I have fix this problem in 1.3.10
