### ISSUE TITLE
maybe a bug in split-row?

### ISSUE THREAD

**Issue by JSchmidt63** [fishedee/antd-formily-boost#6]
Hi,
look at that pics.

i guess the sum isn't correct.

https://fishedee.github.io/antd-formily-boost/components/table/split-row
![components-table-split-row-2021-11-02-A](https://user-images.githubusercontent.com/25293774/139829004-07735a45-2aca-4299-a2c4-bc371de191fb.png)

when i changed the field it is sum correct then.

https://fishedee.github.io/antd-formily-boost/components/table/split-row
![components-table-split-row-2021-11-02-B](https://user-images.githubusercontent.com/25293774/139828186-d151177b-47fa-4be9-bc55-114fe01b4fa4.png)

Cheers :-)

**Comment by JSchmidt63** [comment]
> Hi, look at that pics.
> 
> i guess the sum isn't correct.
> 
> https://fishedee.github.io/antd-formily-boost/components/table/split-row
![components-table-split-row-2021-11-02-A](https://user-images.githubusercontent.com/25293774/139828719-a127f63b-34a0-4a15-a2c8-7ae3d2292a66.png)
> 
> when i changed the field it is sum correct then.
> 
> https://fishedee.github.io/antd-formily-boost/components/table/split-row ![components-table-split-row-2021-11-02-B](https://user-images.githubusercontent.com/25293774/139828186-d151177b-47fa-4be9-bc55-114fe01b4fa4.png)
![components-table-split-row-2021-11-02-A](https://user-images.githubusercontent.com/25293774/139828719-a127f63b-34a0-4a15-a2c8-7ae3d2292a66.png)

**Comment by fishedee** [comment]
init data is wrong, thanks ,I will fix it

**Comment by fishedee** [comment]
Thanks,brother, I have fix this problem in 1.3.10
